version: "3.4"

services:
  app:
    build:
      context: .
    volumes:
      - ./:/app
      # Mount the local gcloud sdk configuration when developing. Note that this
      # will modify the contents on the host.
      - ${CLOUDSDK_CONFIG}/:/tmp/.config/gcloud
    environment:
      - CLOUDSDK_CONFIG=/tmp/.config/gcloud
      - CLOUDSDK_CORE_PROJECT
      - POSTGRES_HOST
      # ensure that the project can access the credentials bucket
      - AWS_SECRET_ACCESS_KEY
      - AWS_ACCESS_KEY_ID
      # variables required for backfill.sh
      - PROJECT=${CLOUDSDK_CORE_PROJECT}
      - START_DS
      - END_DS